### ISSUE TITLE
Bug: complex objects cannot be serialized by noodles

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/fairworkflows#151]
When passing complex objects between functions marked as `is_fairstep`, noodles cannot serialize them:

An example with PIL.Image:
```
@is_fairstep(label='Transform')
def transform(img: Image) -> Image:
    """transform"""
    return img.transpose(Image.ROTATE_90)

@is_fairworkflow(label='My Workflow')
def my_workflow(img):
    """
    workflow
    """
    t1 = transform(img)
    return t1

img = Image.open("img1.png")
fw = my_workflow(img)
fw.execute()
```
Which raises:
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/thread_pool.py", line 21, in modified_target
    return_value = target(*args, **kwargs)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/streams.py", line 271, in patch
    for v in source():
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/streams.py", line 117, in map
    yield from map(self.f, source())
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/run/threading/sqlite3.py", line 36, in pass_job_stream
    status, retrieved_result = db.add_job_to_db(key, job)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/prov/sqlite.py", line 247, in add_job_to_db
    job_msg = self.registry.deep_encode(job)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/serial/registry.py", line 231, in deep_encode
    return deep_map(lambda o: self.encode(o, host), obj)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 103, in deep_map
    return {k: deep_map(f, v) for k, v in result.items()}
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 103, in <dictcomp>
    return {k: deep_map(f, v) for k, v in result.items()}
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 103, in deep_map
    return {k: deep_map(f, v) for k, v in result.items()}
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 103, in <dictcomp>
    return {k: deep_map(f, v) for k, v in result.items()}
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 106, in deep_map
    return [deep_map(f, v) for v in result]
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 106, in <listcomp>
    return [deep_map(f, v) for v in result]
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 103, in deep_map
    return {k: deep_map(f, v) for k, v in result.items()}
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 103, in <dictcomp>
    return {k: deep_map(f, v) for k, v in result.items()}
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 106, in deep_map
    return [deep_map(f, v) for v in result]
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 106, in <listcomp>
    return [deep_map(f, v) for v in result]
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/lib/utility.py", line 100, in deep_map
    result = f(root)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/serial/registry.py", line 231, in <lambda>
    return deep_map(lambda o: self.encode(o, host), obj)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/serial/registry.py", line 187, in encode
    result = enc.encode(obj, make_rec)
  File "/Users/svenvanderburg/opt/anaconda3/envs/fair3.7/lib/python3.7/site-packages/noodles/serial/registry.py", line 342, in encode
    raise NotImplementedError(msg)
NotImplementedError: Cannot encode <PIL.PngImagePlugin.PngImageFile image mode=RGB size=200x200 at 0x7FD00329E450>: encoder for type `PngImageFile` is not implemented.
```

The same thing happens with for example `sklearn.RandomForestClassifier`.

**Comment by svenvanderburg** [comment]
The problem is with serializing for parallel execution. A simple solution would be to instead of `noodles.run_parellel`, use `noodles.run_single`. I quickly tested that and it works.

Supporting parallel execution is a nice-to-have but we can live without it.

**Comment by raar1** [comment]
PR #155 fixes this for now (PIL ```Image``` workflows etc are now possible without error)
